# Stage 1: NPM build
FROM node:22 AS build

# Set directories
WORKDIR /app
COPY . /app

# Install packages and prerender images
RUN npm i
RUN npm run build


# Stage 2: Serve via Nginx
FROM nginx:mainline

# Expose the port Nginx runs on
EXPOSE 80

# Only copy built files into Nginx
COPY --from=build /app/dist/dartegnian-dot-com/browser /usr/share/nginx/html

# Keep Nginx running
CMD ["nginx", "-g", "daemon off;"]